[package]
name = "axum_hello_world"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.1", features = ["tokio"] }
tokio = { version = "1.25.0", features = ["full", "macros", "rt-multi-thread"] }
